server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/vacationdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto : update
  application:
    name: VACATION-SERVICE